### ISSUE TITLE
Looks nice

### ISSUE THREAD

**Issue by thepian** [oklas/intl-webpack-plugin#1]
Your concept looks great, but I'm stomped trying to use it.

```js
import de from 'de.intl'
```

Doesn't make much sense, since there is no such file. I take it that it is supplied by the plugin, but the documentation isn't very clear. You example project didn't help me much as the structure seemed like like the sort of complexity I was trying to avoid.

As I understand it I can make YAML files for translation anywhere in my project, typical beside my component files and then import them in a single place where they can be added to my TranslationService.

It seems that the join plugin can essentially do this for me.

**Comment by thepian** [comment]
I tried for a long time to get it working with Angular 2 + Typescript, I don't know if it clashes with the AotCompiler, it's very hard to figure out where I go wrong without a basic working example.

I tried the import statements, but TypeScript can't make sense of it, so I tried require, but something isn't adding up.

```
ERROR in ./src/app/de.intl
Module build failed: TypeError: Cannot read property 'filter' of undefined
    at Object.module.exports (/Users/Shared/Projects/JurSolution2/src/Swisslex/SlxWebPortal/PortalWebClient/node_modules/join-webpack-plugin/loader.js:33:37)
```

**Comment by oklas** [comment]
Please provide minimal, compleated example which demonstrate problem (better in separated repo). It need to find out why plugin list is not available during building and loading process.

> As I understand it I can make YAML files for translation anywhere in my project, typical beside my component files and then import them in a single place where they can be added to my TranslationService.

There is two way to import:

* import each translation file of component directly in its component (or in any js source file beside).
* use glob `search` param in plugin options - it will search for files by pattern and do import them.

After importing files, them will be splitted into groups (tipically group per language) and then files in each group will be merged into result json file.

**Comment by oklas** [comment]
Feel free to reopen if any additionan information available or create new.
